# Generated by Django 5.1 on 2024-11-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('property_size', models.CharField(max_length=200)),
                ('distance_to_junction', models.CharField(max_length=500)),
                ('picture1', models.ImageField(upload_to='hostel_pictures/')),
                ('picture2', models.ImageField(upload_to='hostel_pictures/')),
                ('picture3', models.ImageField(upload_to='hostel_pictures/')),
                ('picture4', models.ImageField(upload_to='hostel_pictures/')),
                ('picture5', models.ImageField(upload_to='hostel_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostelMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='hostel_videos/')),
                ('picture', models.ImageField(upload_to='hostel_pictures/')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propulse_app.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='hostel',
            name='more_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_hostels', to='propulse_app.hostelmedia'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='utilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propulse_app.utility'),
        ),
    ]
