# Generated by Django 5.1 on 2024-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propulse_app', '0002_alter_utility_options_alter_hostel_more_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='utilities',
        ),
        migrations.AddField(
            model_name='hostel',
            name='utilities',
            field=models.ManyToManyField(related_name='hostel_amenities', to='propulse_app.utility'),
        ),
    ]
