# Generated by Django 5.1 on 2024-11-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propulse_app', '0003_remove_hostel_utilities_hostel_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
